name: DEPLOY
on:
   push:
      tags: 
         - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Set up SSH
           uses: webfactory/ssh-agent@v0.9.0
           with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
         - name: Run deploy script
           run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "bash ${{secrets.PATH_TO_SCRIPT}}"
           env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}